// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzORHYaB3d4xts61RmAXp8GLgehCzWzc0',
    appId: '1:235854058352:web:d2e1d9f1b3349efebf35b5',
    messagingSenderId: '235854058352',
    projectId: 'portfolio-app-59366',
    authDomain: 'portfolio-app-59366.firebaseapp.com',
    storageBucket: 'portfolio-app-59366.firebasestorage.app',
    measurementId: 'G-4GRKV6E10C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh0vKmlO-BlrY9vi_Mslo5jGzXn18VHQY',
    appId: '1:235854058352:android:a332fee889aa9448bf35b5',
    messagingSenderId: '235854058352',
    projectId: 'portfolio-app-59366',
    storageBucket: 'portfolio-app-59366.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVVqM62I84AfVYwu-mqFpr2PMFOVu8dKU',
    appId: '1:235854058352:ios:c0afa7ed08fe7e9dbf35b5',
    messagingSenderId: '235854058352',
    projectId: 'portfolio-app-59366',
    storageBucket: 'portfolio-app-59366.firebasestorage.app',
    iosBundleId: 'com.example.akashPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVVqM62I84AfVYwu-mqFpr2PMFOVu8dKU',
    appId: '1:235854058352:ios:c0afa7ed08fe7e9dbf35b5',
    messagingSenderId: '235854058352',
    projectId: 'portfolio-app-59366',
    storageBucket: 'portfolio-app-59366.firebasestorage.app',
    iosBundleId: 'com.example.akashPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzORHYaB3d4xts61RmAXp8GLgehCzWzc0',
    appId: '1:235854058352:web:fdcb9261cee227abbf35b5',
    messagingSenderId: '235854058352',
    projectId: 'portfolio-app-59366',
    authDomain: 'portfolio-app-59366.firebaseapp.com',
    storageBucket: 'portfolio-app-59366.firebasestorage.app',
    measurementId: 'G-QBM70S1MHV',
  );

}